- hosts: [ masters, agents, agents_public]
  become: true
  tasks:

    - name: DC/OS uninstall
      shell: sudo -i /opt/mesosphere/bin/pkgpanda uninstall
      ignore_errors: true

    - name: remove DC/OS configuration
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /opt/mesosphere
        - /etc/mesosphere
        - /tmp/dcos/

- hosts: workstations
  become: true
  tasks:

    - name: Stop Nginx
      docker_container:
        name: dcos_nginx
        state: absent

    - name: Clear install directory
      file: path=/tmp/dcos-install/ state=absent
      ignore_errors: true
