---
# This playbook installs marathon-lb

- name: create configuration directory
  file: path={{ path_tmp }} state=directory mode=0755

- name: generate configuration
  template:
    src: config.json.j2
    dest: "{{ path_tmp }}/marathon-lb-config.json"
    mode: 0644

- name: install package
  shell: "dcos package install marathon-lb --yes --options={{ path_tmp }}/marathon-lb-config.json"
  run_once: true
  register: install_result
  failed_when: install_result.stderr != "Package is already installed" and install_result.stderr != ""
  changed_when: install_result.stderr == ""
  ignore_errors: true

- name: scale instances
  shell: "dcos marathon app update /marathon-lb instances={{ groups['agents_public'] | length }}"
  run_once: true
  when: install_result.stderr == "Package is already installed"
  ignore_errors: true
